Bosnian translation
ContributorCovenant/contributor_covenant pull request #342
Opened 2016-10-24 17:19 UTC by ivana-mcconnell

I know that there are likely some grammatical errors in this as I haven’t written Bosnian in _years_, but I do think that it’s very useful as an opening salvo. Any edits and/or refinements are very welcome!

2016-10-24 17:56 UTC, CoralineAda commented
I've put out a call for native speakers to review. Thanks for starting this @ivana-mcconnell !

2016-10-24 17:58 UTC, ivana-mcconnell commented
No worries! I'm a native speaker but not a native writer (if that makes sense), so I'd love to see how this evolves. 🙂

2016-10-24 18:58 UTC, mislav reviewed
Hi Ivana! I'm not Bosnian but I'm Croatian, and that's close. Thank you for your contribution! I have started reviewing the text, but it seems to me that there needs to be a lot more work done on this before it's ready, as there seem to be a lot of errors with cases. I would like to help rewrite some of the more complex sentences, but I fear that I don't know very well the subtle boundaries of our languages and that I might express myself in Croatian in places where Bosnian is different. So, I suggest that we find someone who is really proficient with the Bosnian language who can make a pass at this. How does that sound?

In Croatian: Zdravo! Meni se čini da je dosta padeža pogrešno u ovom tekstu. Znam da bosanski nije identičan hrvatskom, ali mislim da su nam padeži jednaki. Mislim da trebamo pomoć od nekoga tko trenutno priča bosanski da pregleda ovaj tekst 😄 Znaš li nekoga od tvojih prijatelja/rodbine?

2016-10-24 18:58 UTC, mislav commented on version/1/4/bs/code_of_conduct.md
> +U interesu ohrabrujući otvoren i dobrodošlice okruženje,mi kao saradnici i održavatelji obećamo da za sviju ko učestvuju u našem projektu i zajednicu, njihovo iskustvo  će biti bez uznemiravanje, bez
* U interesu ohrabr**ivanja** otvoren**og** i pristupačnog okruženja ("dobrodošlog" ne funkcionira dobro kao pridjev ovdje)
* obeća**vamo**
* “da za sviju ko učestvuju u našem projektu i zajednicu, njihovo iskustvo  će biti bez uznemiravanje” - ovo mi ne zvuči dobro, jer dosta padeža ne štima, ali za sada nemam bolji prijedlog
* rodni identitet
* orijentacij**e***

2016-10-24 18:58 UTC, mislav commented on version/1/4/bs/code_of_conduct.md
> +Primjeri ponašanja što stvori pozitivno okruženje:
“stvara” je možda bolje?

2016-10-24 18:58 UTC, mislav commented on version/1/4/bs/code_of_conduct.md
> +* Korištenje prijatan i uključiv jezik
prijat**nog** i uključiv**og**

2016-10-24 20:16 UTC, ivana-mcconnell commented
Hi @mislav! Thanks so much for having a look! I'd expected some case and conjugation errors in it, particularly for some of the more complex sentences!

> I don't know very well the subtle boundaries of our languages and that I might express myself in Croatian in places where Bosnian is different.

That's interesting— my family is Serbian, Croatian, and Bosnian, though I grew up speaking the latter. I imagine some of my errors stem from that as well :) Finding someone who writes Bosnian often and fluently to have a look over it would be great! Know anyone?

2016-10-24 20:19 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +U interesu ohrabrujući otvoren i dobrodošlice okruženje,mi kao saradnici i održavatelji obećamo da za sviju ko učestvuju u našem projektu i zajednicu, njihovo iskustvo  će biti bez uznemiravanje, bez
This is also Croatian but this is my attempt at rewritting that passage

U interesu ohrabrivanja otvorenog i pristupačnog okruženja, mi kao saradnici i odrzavatelji obecavamo svima koji ucestvuju u nasem projektu i zajednici da ce njihovo iskustvo biti bez uznemiravanja, bez diskriminacije na osnovu dobi, invalidnosti, nacionalnosti, rodnog identiteta i izraza, nivoa iskustva, drzavljanstva, izgleda, poroda, vjere ili sekusalnog identiteta ili orijentacije.

2016-10-24 20:20 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +* Poštovanje drugačije stanovište i iskustve
Postovanje drugacijeg stanovista i iskustva

2016-10-24 20:20 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +* Pokazivanje empatiju za druge članovi zajednice
Pokazivanje empatije drugim clanovima zajednice

2016-10-24 20:21 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +* Korištenje seksualnog jezik ili neželjene seksualne pažnje
jezik**a**

2016-10-24 20:22 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +* Izdavanje privatnu informaciju, na primjer adresu, bez dozvole
Objava osobnih informacija, npr. kucna adresa bez prethodne dozvole

2016-10-24 20:23 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +* Bilo kakvo drugo ponašanje što bi bilo neprikladno u profesionalnom okruženju.
Bilo kakvo drugo ponasanje koje bi se smatralo neprikladnim u profesionalnom okruzenju.

2016-10-24 20:23 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +## Naši odgovornosti
Nasa odgovornost

2016-10-24 20:28 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +Održavatelji projekta će razjasniti standarde za prihvatljivo ponašanje, i u slučaju neprikladno ponašanje, od njih se očekuje poštene korektivne mjere.
i u slucaju neprikladno**g** ponasanj**a** od njih se ocekuje primena postenih korektivne mjere

2016-10-24 23:01 UTC, triggerNZ commented on version/1/4/bs/code_of_conduct.md
> +Primjeri ponašanja što stvori pozitivno okruženje:
"koja stvaraju"?

2016-10-25 00:09 UTC, triggerNZ requested changes
Croatian speaker here, fairly polluted by years of English so take my comments with a grain of salt, but I do have relatives in Bosnia so am familiar with certain Bosnian words idioms, though not all of them

2016-10-25 00:09 UTC, triggerNZ commented on version/1/4/bs/code_of_conduct.md
> +Ovaj kodeks ponašanja se odnosi na sve projekte i javne prostore gdje pojedinac predstavlja zajednicu. Na primjer, korištenje od službenu e-mail adresu projekta ili ponašanje kao sluzbeni predstavnik
korištenje službene e-mail adrese

... ovo predstavljanje

2016-10-25 00:09 UTC, triggerNZ commented on version/1/4/bs/code_of_conduct.md
> +U slučaju uvredljivog ponašanja, kontaktiraj održavatelje: [E-MAIL ADRESA]
kontaktirajte

2016-10-25 00:10 UTC, triggerNZ commented
@ivana-mcconnell how would you feel about me forking this and doing a HR version?

2016-10-25 03:34 UTC, triggerNZ commented on version/1/4/bs/code_of_conduct.md
> +## Primjenjivanje
Primjena ?

2016-10-25 10:38 UTC, mislav commented
Hvala @vvuksan @triggerNZ na pomoći!

@triggerNZ I'm only speaking for myself here, but I think you'd definitely be welcome to make a Croatian translation based on this Bosnian version. I think the best time to start your HR translation would be when this Bosnian one gets finalized and merged, so there would be less work for you keeping both sides in sync when they are developing in parallel.

2016-10-25 21:10 UTC, ivana-mcconnell commented
@triggerNZ Go for it! 

@mislav — once I make the changes suggested by yourself and @vvuksan, do you think it will be ready, or will it need more review?

2016-10-25 21:18 UTC, mislav commented
@ivana-mcconnell Thanks for making all those updates! Please ping the thread after you're done and I think that it will be enough that at least one of us giving our 👍 should be enough for this to be considered mergeable.

2016-10-26 00:04 UTC, vvuksan commented on version/1/4/bs/code_of_conduct.md
> +Svaki izvještaj će se istražiti, i odgovor će biti fer i prikladan za situaciju. Održavatelji projekta su odgovorni da održavaju povjerljivost za svaki izvještaj. Dodatne detalje polisa mogu biti obj
Mislim da je izvjestaj pretjerano kruto. Mislim da je bolje reci zalba (poput knjige zalbi) znaci

Svaka zalba ce se istraziti i odgovor ce biti fer i prikladan za situaciju. Odrzavatelji projekta su odgovorni odrzati povjerljivost svake zalbe.

2016-10-26 17:59 UTC, ivana-mcconnell commented
@mislav @vvuksan @triggerNZ I've made the changes, let me know if I've missed anything!

2016-10-27 18:25 UTC, ivana-mcconnell commented
@CoralineAda this might be ready to merge now? :)

2016-10-27 18:48 UTC, merged

2016-10-27 18:49 UTC, CoralineAda commented
Thanks for your hard work!

2021-03-13 22:12 UTC, KunKax reviewed
!

2023-06-03 14:09 UTC, Alex43ice reviewed
- []()![google_privacy_policy_en_us.pdf](https://github.com/EthicalSource/contributor_covenant/files/11642943/google_privacy_policy_en_us.pdf)

2023-06-03 14:11 UTC, Alex43ice reviewed
Thanks 👍

2023-06-03 14:12 UTC, Alex43ice reviewed
[]()https://github.com/orgs/community/discussions

2023-06-03 14:13 UTC, Alex43ice reviewed
Awesome

2023-06-03 14:14 UTC, Alex43ice commented
Great

2024-01-12 12:34 UTC, DEN19875 commented on version/1/4/bs/code_of_conduct.md
> +Svaki izvještaj će se istražiti, i odgovor će biti fer i prikladan za situaciju. Održavatelji projekta su odgovorni da održavaju povjerljivost za svaki izvještaj. Dodatne detalje polisa mogu biti obj
![README.md](https://github.com/EthicalSource/contributor_covenant/files/13919103/README.md)

_

2024-01-12 12:35 UTC, DEN19875 commented on version/1/4/bs/code_of_conduct.md
> +Svaki izvještaj će se istražiti, i odgovor će biti fer i prikladan za situaciju. Održavatelji projekta su odgovorni da održavaju povjerljivost za svaki izvještaj. Dodatne detalje polisa mogu biti obj
-```
- - [ ] # > `~~@![Резервные коды.pdf](https://github.com/EthicalSource/contributor_covenant/files/13919112/default.pdf)

 ~~`
```

2024-01-12 12:36 UTC, DEN19875 commented on version/1/4/bs/code_of_conduct.md
> +Svaki izvještaj će se istražiti, i odgovor će biti fer i prikladan za situaciju. Održavatelji projekta su odgovorni da održavaju povjerljivost za svaki izvještaj. Dodatne detalje polisa mogu biti obj
> ![README.md](https://github.com/EthicalSource/contributor_covenant/files/13919103/README.md)
> 
> _

2024-01-12 12:45 UTC, DEN19875 commented on version/1/4/bs/code_of_conduct.md
> +Svaki izvještaj će se istražiti, i odgovor će biti fer i prikladan za situaciju. Održavatelji projekta su odgovorni da održavaju povjerljivost za svaki izvještaj. Dodatne detalje polisa mogu biti obj
[](![Screenshot_2024-01-12-13-24-34-857_com.chrome.beta.jpg](https://github.com/EthicalSource/contributor_covenant/assets/155088735/aff8cfe4-b813-4e0c-a586-26806deb28be)