Initial commit for the Japanese translation 1.4
ContributorCovenant/contributor_covenant pull request #344
Opened 2016-10-29 09:10 UTC by TatchNicolas

Tried to translate based on the expressions used in version 1.3, but I paraphrased when I felt there's an better way.

 I'd like to have opinions of other translators, including translators for other languages.

2016-10-30 10:01 UTC, TatchNicolas commented on version/1/4/ja/code_of_conduct.md
> +* 性的な言葉・画像の使用および
Oh yes I missed a part of the list item...I'll fix it soon. I should've checked more carefully...

2017-03-02 05:18 UTC, ykzts requested changes

2017-03-02 05:18 UTC, ykzts commented on version/1/4/ja/code_of_conduct.md
> +されている [コントリビュータ協定][homepage] バーlョン 1.4 に適合しています。
> バーlョン

why? "バージョン" is correct.

2017-03-12 02:43 UTC, TatchNicolas commented on version/1/4/ja/code_of_conduct.md
> +されている [コントリビュータ協定][homepage] バーlョン 1.4 に適合しています。
Such a stupid type of me...Thanks for pointing out.

2017-03-12 02:50 UTC, ykzts approved these changes

2017-03-16 11:28 UTC, rintaro commented on version/1/4/ja/code_of_conduct.md
> +よびメンテナとして、年齢、体系、障碍、民族、性自認や性別表現、経験の多
体系 => 体型

2017-03-18 05:48 UTC, TatchNicolas commented on version/1/4/ja/code_of_conduct.md
> +よびメンテナとして、年齢、体系、障碍、民族、性自認や性別表現、経験の多
TXT version also had the same typo, already fixed. Thanks.

2018-09-25 03:21 UTC, closed without merging