Thai translation
ContributorCovenant/contributor_covenant pull request #406
Opened 2017-05-22 04:58 UTC by osuvic

2017-06-07 22:46 UTC, CoralineAda commented
Hey there! Thanks for this. I'm looking now for a native Thai speaker to review the translation.

2017-12-29 03:25 UTC, Roshanjossey commented
@sTatiyanupanwong, could you please do a review of this translation?

2017-12-29 04:13 UTC, SupasinTatiyanupanwong requested changes

2017-12-29 04:13 UTC, sTatiyanupanwong commented on version/1/4/th/code_of_conduct.md
> +* เผยแพร่ข้อมูลส่วนตัวของผู้อื่นเช่น ที่อยู่ อีเมล์ เฟสบุ๊ค โดยไม่ได้รับอนุญาต
I don't think เฟสบุ๊ค is suitable in this context.
E-mail in Thai is อีเมล not อีเมล์

2017-12-29 04:13 UTC, sTatiyanupanwong commented on version/1/4/th/code_of_conduct.md
> +ผู้ดูแลโครงการมีสิทธิ์และหน้าที่รับผิดชอบในการลบ แก้ไขหรือ ปฏิเสธความคิดเห็น, commits, wiki edits โค้ด, , ปัญหาต่างๆและผลงานอื่น ๆที่ไม่สอดคล้องกับหลักจรรยาบรรณนี้หรือ ไม่อนุญาตให้มีส่วนร่วมอย่างชั่ว
Remove comma, fix spacing and grammar
ในพจนานุกรม ฉบับราชบัณฑิตยสถาน ทั้งฉบับ พ.ศ. 2525 และฉบับ พ.ศ. 2542 เขียนไม้ยมกโดยเว้นวรรคทั้งหน้าและหลังไม้ยมก  เช่น  "ไม้ไผ่ลำยาว ๆ" และ "ติด ๆ กัน"

2017-12-29 04:13 UTC, sTatiyanupanwong commented on version/1/4/th/code_of_conduct.md
> + ทีมงานโครงการจำเป็นต้องรักษาความลับเกี่ยวกับผู้ให้ข้อมูลของเหตุการณ์
Unwanted space character at first index here.
All of comments here in this file also apply to other files in this PR.

2017-12-29 06:17 UTC, Roshanjossey commented
@sTatiyanupanwong, Thank you so much for your review.

@osuvic, Could you please address the review comments and make necessary changes?

2018-01-03 01:02 UTC, casusa1991 approved these changes

2018-09-25 03:22 UTC, closed without merging