Update CODE_OF_CONDUCT.md
ContributorCovenant/contributor_covenant pull request #500
Opened 2018-01-14 18:39 UTC by tanya-vedi

2018-01-14 18:39 UTC, tanya-vedi commented
#498

2018-01-28 02:25 UTC, ianbollinger commented on CODE_OF_CONDUCT.md
> +This project is governed by the [Contributor Covenant version 1.4] (https://www.contributor-covenant.org/version/1/4/code-of-conduct.html). All contributors and participants agree to abide by its ter
The link appears to be broken on GitHub's markdown renderer. While I think the original Markdown implementation allowed a space between the `]` and `(` characters in a link, both GitHub Flavored Markdown and CommonMark seem to disallow it. Anyway, that was probably more verbiage than an extraneous space warranted, sorry.

2018-02-28 03:59 UTC, jordan2936 requested changes
Parts Need to delete

2018-02-28 04:00 UTC, jordan2936 approved these changes

2018-02-28 04:00 UTC, jordan2936 commented on CODE_OF_CONDUCT.md
> -This project is governed by the Contributor Covenant version 1.4 (https://www.contributor-covenant.org/version/1/4/code-of-conduct.html). All contributors and participants agree to abide by its terms
Delete

2018-09-25 03:22 UTC, closed without merging