Italian translation of version 1.4
ContributorCovenant/contributor_covenant pull request #581
Opened 2018-09-21 10:50 UTC by lucab85

Italian translation of version 1.4

2018-09-21 22:28 UTC, CoralineAda commented
Hi! I'm going to track down some other native speakers to review the translation. Thanks a ton for your work!

2018-09-23 23:05 UTC, barisione requested changes

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +## Il nostro Impegno
This capitalisation style (every word capitalised) is less common in Italian than in English.
If you decide to use it, why not capitalise “nostro” (“our”)?

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +dall'età, dal corpo dimensione, disabilità, etnia, caratteristiche sessuali,
“Corpo dimensione” is not correct.  “Corporatura”?

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +socio-economico, nazionalità, personale aspetto, razza, religione o identità e
“Personale aspetto” is wrong. Simply “aspetto”?

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* Usare un linguaggio accogliente e inclusivo
I think that not using infinitive here woud be more idiomatic here (and in the following items). “Uso di un ...”

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* Essere rispettosi di punti di vista ed esperienze differenti
“Rispetto ...”

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* Accettare con garbo la critica costruttiva
Maybe “Accettazione di critiche costruttive con garbo”? (i.e. I think plural is more correct).

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* Concentrarsi su ciò che è meglio per la comunità
“Concentrazione ...” but I don't think the sentence would sound that good but I cannot think of a better word!

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* Mostrare empatia nei confronti degli altri membri della comunità
“Empatia ...”

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* L'uso di linguaggio o immagini sessualizzate e l'attenzione sessuale o
“Attenzione sessuale” is a literal translation from English and doesn't mean much.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +  advances indesiderate
You usually don't add plurals for foreign words (even if this rule is often used inconsistently).

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* Troll, commenti offensivi / offensivi e attacchi personali o politici
“Comportamenti da troll”.
You repeated “offensivi” twice.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* Molestie pubbliche o private
“in pubblico o privato”? I'm not 100% sure but I think it sounds more idiomatic.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +* Pubblicare informazioni private altrui, ad esempio un indirizzo fisico o
You haven't used the infinitive in any other item, so it's better avoided here as well.
“Pubblicazione di informazioni ...”

I'm not sure “indirizzo fisico” is the most correct way of saying this. I had to google it and it looks it's mainly used to talk about MAC addresses on in documents which are translated from English.
“indirizzo postale” is, I think, the more common way of saying this.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +comportamenti accettati e sono tenuti a intraprendere azioni correttive
“comportamento” (i.e. singular) and “accettabili”.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +modificare o rifiutare commenti, commit, codice, modifiche wiki, issue e altri
Maybe “modifiche del wiki”? (or “dei” plural)
It's always difficult when you mix English and Italian, but try to replace wiki with an italian word, for instance “documenti”, you wouldn't say “modifiche documenti”, but “modifiche dei documenti”.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +contributi non allineati a questo Codice di Comportamento, o di vietare
“vietare [...] qualsiasi contributore” is not correct. It would be “vietate [...] a qualsiasi contributore di ...”, but then the sentence would need to be deeply modified to make it work.

Using “escludere” instead of “vietare” would allow you to keep the sentence more similar.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +temporaneamente o permanentemente qualsiasi contributore per altri
Very minor, but I think the sentence would flow better if you put “temporaneamente o permanentement” in a pair of commas.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +comportamenti che essi ritengono inappropriato, minaccioso, offensivo o dannoso.
“comportamenti ritenuti” and the plurals.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +Le istanze di comportamento abusivo, molesto o altrimenti inaccettabile possono
“casi” instead of “istanze”?

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +essere presentate contattando il team di progetto all'indirizzo
“team del progetto”

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +luogo ad una risposta ritenuta necessaria e appropriata alle circostanze. Il
“a una” instead of “ad una”? They are both fine, but then it's slightly better[1] not to add the “d” if the vowel is not the same in the following word (as you do later by saying “e appropriata” instead of “ed appropriata”).

[1] Or, at least, that's what my teachers always told me ;)

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +team di progetto è obbligato a mantenere la riservatezza per quanto riguarda il
“del” like agove

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +mittente di un incidente.
“mittente” is “sender”. I'm not sure how to say “reporter” in the best way in this context. Maybe the long form “la persona che ha riportato ...”

“incidente” is mainly used for things like car accidents. Here you may prefer “caso” or “episodio”.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +I manutentori del progetto che non rispettano o applicano il Codice di
I'd use the subjunctive form “rispettino” and “applichino”.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +permanenti come determinato da altri membri di direzione del progetto.
“membri alla guida del progetto”

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +Questo Codice di Comportamento è adattato da [Contributor Covenant][homepage],
“adattato dal”

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +Nell'interesse di promuovere un ambiente aperto e accogliente, noi come
“della promozione di”.

While the sentence sounds find in English, in Italian I think it would sound better if you just said “noi contributori e ...”.

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +contributori e manutentori ci impegnamo a partecipare al nostro progetto e
You missed a bit (“making”) here.
Maybe “ci impegnamo a rendere la partecipazione al nostro progetto e alla nostra ...”

2018-09-23 23:05 UTC, barisione commented on content/version/1/4/code-of-conduct.it.md
> +la nostra comunità un'esperienza senza molestie per tutti, indipendentemente
maybe s/senza/libera da/?

2018-09-23 23:24 UTC, barisione commented
From a gender neutral point of view your translation is as good as you can get with current Italian (where, unfortunately, masculine is the “generic” form) without using longer forms and weird expressions. I'm not sure what should be done about it.

I did look at the most recent change to the French translation (which is about this problem), but the changes don't necessarily all apply to Italian.

Small intro for non Italian speakers, in Romance languages all words have a gender. The same word can be made feminine/masculine based on whether it refers to something feminine or masculine (“dottore” is a male doctor, “dottoressa” is a female doctor).
Some words are not adapted to what they refer to even if the word has a gender. For instance “persona” (“person”) is feminine but is used to refer to both male and female people.

An example of potentially problematic translation of this document is the word “maintainer” which is “manutentore” (masc) / “manutentrice” (fem), and “maintainers” is “manutentori” (masc) / “manutentrici” (fem).
Your translation is 100% correct according to current Italian rules but the rules as not necessarily a reflection of a modern more inclusive world.
A way to avoid that could be to say something like “the people who maintain the project” (“le persone che mantengono il progetto“), but it sounds really really bad.

2018-09-24 07:26 UTC, skylarmt commented
@barisione Do many native speakers worry about gendered nouns in their languages, or are you just trying to be super politically correct for the sake of political correctness?  From my experience, Romance languages are done that way because (like you said) it sounds better.

If the maintainer of a project is female, she can decide to use the feminine version of the word, and vice versa for a male maintainer.  That's what the Creative Commons license is for.  The whole thing is a non-issue.  If people feel oppressed by their *language*, their time might be better spent in therapy than whining on the Internet about grammar.

I really hope you're trolling...

2018-09-24 11:37 UTC, barisione commented
> @barisione Do many native speakers worry about gendered nouns in their languages, or are you just trying to be super politically correct for the sake of political correctness?

It's mainstream enough to have discussions on TV/newspapers about it (a couple of years ago it was about what the proper feminine for “mayor” is).

> From my experience, Romance languages are done that way because (like you said) it sounds better.

I don't care about what the maintainers of the Contributor Covenant decide (there are pros and cons), but it's not my call. I'm just somebody who volunteered to review this pull request. What I did is just explain how things stand as it's clear that this project cares (due to similar changes to the French version).

> The whole thing is a non-issue. If people feel oppressed by their language, their time might be better spent in therapy than whining on the Internet about grammar.

Nice! I see you really understood the spirit of the Contributor Covenant!

2018-09-24 13:40 UTC, lucab85 commented
@barisione I AGREE with your vision about the Italian language. I'm going to update the commit in the upcoming days.

2018-09-25 03:22 UTC, closed without merging

2018-09-25 03:53 UTC, CoralineAda commented
I renamed 'master' to 'release', so you'll need to rebase and reopen this PR.