Chinese translation v2.0
ContributorCovenant/contributor_covenant pull request #745
Opened 2020-01-06 20:21 UTC by liyishuai

2020-01-06 20:22 UTC, CoralineAda commented
Thanks @liyishuai! I'll put out a call for other native speakers to review the translation. Your effort is greatly appreciated! 🖤

2020-11-28 10:29 UTC, kj415j45 requested changes

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +# 参与者公约
个人认为"Contributor"还是翻译为“贡献者”
```suggestion
# 贡献者公约
```

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +* 尊重不同的主张、观点和经验
```suggestion
* 尊重不同的主张、观点和经历
```

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +* 积极提出、耐心接受有益批评
```suggestion
* 积极提出、耐心接受建设性意见
```

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +* 未获明确授权擅自发布他人的资料，如地址、电子邮箱等
```suggestion
* 公开他人的隐私信息，例如未经其许可公开其物理地址或邮箱地址
```

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +社区负责人有权利和义务删除、编辑、拒绝违背本标准的评论（comment）、提交（commit）、代码、维基（wiki）编辑、问题（issue）等贡献。如有必要，需告知采取措施之理由。
```suggestion
社区负责人有权利和义务删除、编辑、拒绝违背本公约的评论（comment）、提交（commit）、代码、维基（wiki）编辑、问题（issue）等贡献。如有必要，需告知采取措施之理由。
```

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +如遇滥用、骚扰等不当行为，请通过［在此输入联系方式］向纪律检查委员举报。
这里原文是"community leaders"，译为“纪律检查委员”不妥。下同。

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +纪委将审议并调查全部投诉。
```suggestion
纪委将迅速审议并调查全部投诉。
```

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +**处理意见**：警告继续违纪之后果、违纪者在特定时间内禁止与当事人往来、不得擅自与社区执法者往来，禁令涵盖社区内外、社交网络在内的一切联络。如有违反，可致封禁乃至开除。
```suggestion
**处理意见**：警告继续违纪之后果、违纪者在特定时间内禁止与当事人往来、不得擅自与社区执法者往来，禁令涵盖社区内以及社区外包括社交媒体在内的一切联络。如有违反，可致封禁乃至开除。
```

2020-11-28 10:29 UTC, kj415j45 commented on content/version/2/0/code_of_conduct.zh-cn.md
> +## 来源
需同步上游更新

2020-11-28 11:53 UTC, liyishuai reviewed
Thanks for your review! I've merged some suggestions while others are still under discussion.

2020-11-28 11:53 UTC, liyishuai commented on content/version/2/0/code_of_conduct.zh-cn.md
> +* 积极提出、耐心接受有益批评
“建设性”系直译，其语义不清，故主张本土化为“有益”。

2020-11-28 11:53 UTC, liyishuai commented on content/version/2/0/code_of_conduct.zh-cn.md
> +* 未获明确授权擅自发布他人的资料，如地址、电子邮箱等
“Physical”直译为“物理”欠妥。

2020-11-28 11:53 UTC, liyishuai commented on content/version/2/0/code_of_conduct.zh-cn.md
> +如遇滥用、骚扰等不当行为，请通过［在此输入联系方式］向纪律检查委员举报。
此处本土化确实激进，但不妨取其字面意思，负责调查的community leader自然可称为纪委。

2020-11-28 11:53 UTC, liyishuai commented on content/version/2/0/code_of_conduct.zh-cn.md
> +**处理意见**：警告继续违纪之后果、违纪者在特定时间内禁止与当事人往来、不得擅自与社区执法者往来，禁令涵盖社区内外、社交网络在内的一切联络。如有违反，可致封禁乃至开除。
“社区”一词重复出现，故主张合并为“内外”。

2021-05-12 10:44 UTC, ongweiloon777 approved these changes

2021-05-23 02:08 UTC, liyishuai commented
@CoralineAda Ready to merge.

2021-05-23 02:20 UTC, CoralineAda commented
Thank you @ liyishuai!

2021-05-23 02:20 UTC, merged

2021-06-02 16:04 UTC, invictus80 approved these changes

2021-06-02 16:17 UTC, Jacobwer reviewed
Gracias

2021-06-02 17:05 UTC, Jacobwer reviewed
Perfecto muchas gracias