Updated governance, contributing, and code of conduct
ContributorCovenant/contributor_covenant pull request #959
Opened 2021-06-07 17:45 UTC by CoralineAda

## Summary

1. Changes to the governance model and code of conduct related to the change in stewardship of Contributor Covenant.
2. Updated and reorganized the contributing guide.

2021-06-26 16:45 UTC, berax574 requested changes

2021-06-26 16:45 UTC, berax574 commented on GOVERNANCE.md
> +[Creative Commons BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)
Yxyxucuctsyfuci

2021-07-05 18:32 UTC, merged

2022-09-30 07:04 UTC, tuxtvixx commented
Nice..

2022-09-30 07:04 UTC, tuxtvixx commented
> ## Summary
> 
> 1. Changes to the governance model and code of conduct related to the change in stewardship of Contributor Covenant.
> 2. Updated and reorganized the contributing guide.
>

2022-09-30 07:06 UTC, tuxtvixx commented
Nice..

2022-09-30 07:10 UTC, tuxtvixx commented
Fantastic.. One more step behind..